// The tri-coach container app. Deploy after main.bicep, and after the four Key
// Vault secrets below have real values — the app fails to start a revision if a
// referenced secret does not exist yet.
targetScope = 'resourceGroup'

param name string = 'tricoach'
param location string = resourceGroup().location

@description('From main.bicep outputs.')
param environmentId string
param identityId string
param acrLoginServer string
param keyVaultUri string

@description('Image tag. Avoid "latest" — a fixed tag is what makes a rollback possible.')
param imageTag string

// --- Non-secret configuration --------------------------------------------
param coachModel string = 'claude-sonnet-5'
param plannerModel string = 'claude-opus-5'
param intervalsAthleteId string
param telegramAllowedChatId string
param vaultRepo string
param gitAuthorName string = 'tri-coach'
param gitAuthorEmail string = 'coach@localhost'
param timeZone string = 'Europe/Copenhagen'
// When the morning job starts polling for the night's wellness — it briefs as
// soon as HRV, resting HR and sleep publish, and gives up at the deadline.
// Keep these in step with .env.example and CLAUDE.md.
param dailyBriefHour int = 6
param dailyBriefMinute int = 0
param dailyBriefDeadlineHour int = 9
param dailyBriefDeadlineMinute int = 0
param wellnessPollIntervalMin int = 10

// When the evening debrief runs. A fixed time, not a poll window any more:
// session notes are written per activity by the webhook as uploads land, so by
// 21:00 there is nothing left to wait for. This job writes the daily note; the
// brief does not. Keep in step with .env.example and CLAUDE.md.
param dailyDebriefHour int = 21
param dailyDebriefMinute int = 0

@description('Port the intervals.icu webhook receiver listens on. Must match the ingress targetPort.')
param webhookPort int = 8080

@description('Calendars snapshotted into 00 Meta/calendar.md. Comma-separated ids, or "primary".')
param googleCalendarIds string = 'primary'

// Key Vault secret names. Values are set out-of-band with `az keyvault secret set`
// so no secret ever passes through a template, a parameter file, or a deployment
// history entry.
// The Google client id is not a credential on its own, but it is kept here with
// the rest of the OAuth material rather than in the parameter file so the whole
// grant lives in one place.
var secretNames = {
  anthropic: 'anthropic-api-key'
  intervals: 'intervals-api-key'
  telegram: 'telegram-bot-token'
  vaultSshKey: 'vault-ssh-key'
  googleClientId: 'google-health-client-id'
  googleClientSecret: 'google-health-client-secret'
  googleHealthRefresh: 'google-health-refresh-token'
  googleCalendarRefresh: 'google-calendar-refresh-token'
  // Generated by intervals.icu, not by us: it is shown on the app's page at
  // https://intervals.icu/settings/apps and arrives in the body of every webhook
  // POST. The receiver refuses to open a port without it, so this secret is
  // what turns the feature on.
  intervalsWebhookSecret: 'intervals-webhook-secret'
}

resource app 'Microsoft.App/containerApps@2024-03-01' = {
  name: '${name}-bot'
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identityId}': {} }
  }
  properties: {
    managedEnvironmentId: environmentId
    configuration: {
      activeRevisionsMode: 'Single'
      // There is now exactly one thing to serve: the intervals.icu
      // ACTIVITY_UPLOADED webhook. It cannot be long-polled the way Telegram is
      // — intervals.icu has to be able to reach us — so the "no public surface"
      // property this app used to have is genuinely gone. Everything else is
      // still outbound.
      //
      // What defends it: the receiver compares the `secret` in each POST body
      // against the Key Vault value with a constant-time compare and drops
      // anything that fails, and it opens no port at all when that secret is
      // unset. Ingress terminates TLS here, and allowInsecure is false so there
      // is no plaintext listener to downgrade to.
      ingress: {
        external: true
        targetPort: webhookPort
        transport: 'auto'
        allowInsecure: false
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }
      registries: [
        {
          server: acrLoginServer
          identity: identityId
        }
      ]
      secrets: [
        {
          name: secretNames.anthropic
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.anthropic}'
          identity: identityId
        }
        {
          name: secretNames.intervals
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.intervals}'
          identity: identityId
        }
        {
          name: secretNames.telegram
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.telegram}'
          identity: identityId
        }
        {
          name: secretNames.vaultSshKey
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.vaultSshKey}'
          identity: identityId
        }
        // One OAuth client, two refresh tokens, and they must stay separate: the
        // Google Health API 403s a token that also carries the calendar scope.
        {
          name: secretNames.googleClientId
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.googleClientId}'
          identity: identityId
        }
        {
          name: secretNames.googleClientSecret
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.googleClientSecret}'
          identity: identityId
        }
        {
          name: secretNames.googleHealthRefresh
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.googleHealthRefresh}'
          identity: identityId
        }
        {
          name: secretNames.googleCalendarRefresh
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.googleCalendarRefresh}'
          identity: identityId
        }
        {
          name: secretNames.intervalsWebhookSecret
          keyVaultUrl: '${keyVaultUri}secrets/${secretNames.intervalsWebhookSecret}'
          identity: identityId
        }
      ]
    }
    template: {
      containers: [
        {
          name: 'coach'
          image: '${acrLoginServer}/tri-coach:${imageTag}'
          resources: {
            // 2 vCPU / 4Gi is the top of the Consumption profile and the smallest
            // size that fits the Claude Code CLI plus the bot plus the MCP server.
            cpu: json('2.0')
            memory: '4.0Gi'
          }
          env: [
            { name: 'ANTHROPIC_API_KEY', secretRef: secretNames.anthropic }
            { name: 'INTERVALS_API_KEY', secretRef: secretNames.intervals }
            { name: 'TELEGRAM_BOT_TOKEN', secretRef: secretNames.telegram }
            { name: 'COACH_MODEL', value: coachModel }
            { name: 'PLANNER_MODEL', value: plannerModel }
            { name: 'INTERVALS_ATHLETE_ID', value: intervalsAthleteId }
            { name: 'TELEGRAM_ALLOWED_CHAT_ID', value: telegramAllowedChatId }
            { name: 'VAULT_REPO', value: vaultRepo }
            { name: 'VAULT_PATH', value: '/vault' }
            { name: 'GIT_AUTHOR_NAME', value: gitAuthorName }
            { name: 'GIT_AUTHOR_EMAIL', value: gitAuthorEmail }
            { name: 'TZ', value: timeZone }
            { name: 'DAILY_BRIEF_CRON_HOUR', value: string(dailyBriefHour) }
            { name: 'DAILY_BRIEF_CRON_MINUTE', value: string(dailyBriefMinute) }
            { name: 'DAILY_BRIEF_DEADLINE_HOUR', value: string(dailyBriefDeadlineHour) }
            { name: 'DAILY_BRIEF_DEADLINE_MINUTE', value: string(dailyBriefDeadlineMinute) }
            { name: 'WELLNESS_POLL_INTERVAL_MIN', value: string(wellnessPollIntervalMin) }
            { name: 'DAILY_DEBRIEF_CRON_HOUR', value: string(dailyDebriefHour) }
            { name: 'DAILY_DEBRIEF_CRON_MINUTE', value: string(dailyDebriefMinute) }
            // Unset this and the receiver never opens a port, leaving the bot
            // behaving exactly as it did before webhooks existed.
            { name: 'INTERVALS_WEBHOOK_SECRET', secretRef: secretNames.intervalsWebhookSecret }
            { name: 'WEBHOOK_PORT', value: string(webhookPort) }
            // Without these the wellness sync dies every morning on a missing
            // refresh token and the calendar snapshot silently goes stale — the
            // agent's only wellness numbers come through this sync.
            { name: 'GOOGLE_HEALTH_CLIENT_ID', secretRef: secretNames.googleClientId }
            { name: 'GOOGLE_HEALTH_CLIENT_SECRET', secretRef: secretNames.googleClientSecret }
            { name: 'GOOGLE_HEALTH_REFRESH_TOKEN', secretRef: secretNames.googleHealthRefresh }
            { name: 'GOOGLE_CALENDAR_REFRESH_TOKEN', secretRef: secretNames.googleCalendarRefresh }
            { name: 'GOOGLE_CALENDAR_IDS', value: googleCalendarIds }
            // entrypoint.sh copies this to /root/.ssh and chmods it to 600.
            { name: 'VAULT_SSH_KEY_FILE', value: '/mnt/secrets/id_ed25519' }
          ]
          volumeMounts: [
            {
              volumeName: 'vault-ssh'
              mountPath: '/mnt/secrets'
            }
          ]
        }
      ]
      volumes: [
        {
          name: 'vault-ssh'
          storageType: 'Secret'
          secrets: [
            {
              secretRef: secretNames.vaultSshKey
              path: 'id_ed25519'
            }
          ]
        }
      ]
      scale: {
        // Pinned to exactly one replica, and this is not negotiable: Telegram
        // allows a single getUpdates poller per token, so a second replica makes
        // both replicas fail with 409 Conflict. minReplicas 1 also keeps the
        // 06:30 APScheduler job alive — scale-to-zero would silently kill it.
        minReplicas: 1
        maxReplicas: 1
      }
    }
  }
}

output appName string = app.name
// The URL to paste into the app's Webhook URLs at
// https://intervals.icu/settings/apps is this plus /intervals/webhook. It is
// stable across revisions, so it only has to be set there once.
output appFqdn string = app.properties.configuration.ingress.fqdn
